<?php

namespace BeycanPress\Tokenico;

class Lang
{
    public static function get() : array
    {
        return [
            "connect" => esc_html__('Connect wallet', 'tokenico'),
            "notDetected" => esc_html__('The wallet you want to connect to could not be detected!', 'tokenico'),
            "waitingConnection" => esc_html__("Establishing connection please wait!", 'tokenico'),
            "waiting" => esc_html__('Waiting...', 'tokenico'),
            "walletTitle" => esc_html__('Please connect to a wallet to continue', 'tokenico'),
            "connectionRefused" => esc_html__('Connection refused', 'tokenico'),
            "notSupportedChain" => esc_html__('You are currently on an unsupported network, please try again after passing one of the supported networks', 'tokenico'),
            "connectedWallet" => esc_html__('Connected wallet: ', 'tokenico'),
            "activeChain" => esc_html__('Active chain: ', 'tokenico'),
            "connectedAccount" => esc_html__('Connected account: ', 'tokenico'),
            "orderPrice" => esc_html__('Order price: ', 'tokenico'),
            "donateAmount" => esc_html__('Donate amount: ', 'tokenico'),
            "donate" => esc_html__('Donate', 'tokenico'),
            "pleaseEnterDonateAmount" => esc_html__('Please enter donation amount', 'tokenico'),
            "confirmDonate" => esc_html__('Confirm donate', 'tokenico'),
            "donateRejected" => esc_html__('Donate rejected', 'tokenico'),
            "paymentPrice" => esc_html__('Payment price: ', 'tokenico'),
            "paymentCurrency" => esc_html__('Payment currency: ', 'tokenico'),
            "notCurrencySelected" => esc_html__('Not currency selected', 'tokenico'),
            "notCurrencySelectedPay" => esc_html__('Please select the currency you want to pay in', 'tokenico'),
            "notCurrencySelectedDonate" => esc_html__('Please select the currency you want to donate in', 'tokenico'),
            "payWith" => esc_html__('Pay with', 'tokenico'),
            "confirmPayment" => esc_html__('Confirm payment', 'tokenico'),
            "cancel" => esc_html__('Cancel', 'tokenico'),
            "confirm" => esc_html__('Confirm', 'tokenico'),
            "insufficientBalance" => esc_html__('Insufficient balance!', 'tokenico'),
            "paymentRejected" => esc_html__('Payment rejected', 'tokenico'),
            "paymentFailed" => esc_html__('Payment not verified via Blockchain', 'tokenico'),
            "unexpectedError" => esc_html__('An unexpected error has occurred', 'tokenico'),
            "pleaseWait" => esc_html__('Please wait...', 'tokenico'),
            "confirmWithWallet" => esc_html__('Confirm this action in your wallet', 'tokenico'),
            "verifyTransaction" => esc_html__('Awaiting verification of payment via blockchain. Please do not close the page.', 'tokenico'),
            "transactionId" => esc_html__('Transaction Id: ', 'tokenico'),
            "notFoundAcceptedWallets" => esc_html__('No active wallets found, please contact the site administrator.', 'tokenico'),
            "notFoundAcceptedChains" => esc_html__('No active chains found, please contact the site administrator.', 'tokenico'),
            "completedDonate" => esc_html__('Donation sent successfully', 'tokenico'),
            "completedPayment" => esc_html__('Payment completed successfully', 'tokenico'),
            "disconnect" => esc_html__('Disconnect', 'tokenico'),
            'supportedNetworks' => esc_html__('Supported networks', 'tokenico'),
            'problemConvertingCurrency' => esc_html__('There was a problem converting currency!', 'tokenico'),
            'intrinsicGasTooLow' => esc_html__('Intrinsic gas too low', 'tokenico'),
            "chainChanged" => esc_html__("Network change detected page will reload.", 'tokenico'),
            "notAcceptedCurrency" => esc_html__("Not accepted currency", 'tokenico'),
            "timeOut" => esc_html__('The operation timed out, The page will reload.', 'tokenico'),
            "discountRate" => esc_html__("{discountRate}% discount on purchases with this coin.", 'tokenico'),
            "connectionFailed" => esc_html__("There was a problem establishing the connection!", 'tokenico'),
            "notFoundInfuraId" => esc_html__("Infura id is required for WalletConnect", 'tokenico'),
            'fieldCannotBeEmpty' => esc_html__('"%s" field cannot be left blank.', 'tokenico'),
            'confirm' => esc_html__('Confirm', 'tokenico'),
            'cancel' => esc_html__('Cancel', 'tokenico'),
            'confirmNetwork' => esc_html__('You are about to publish the contract on network "%s". Do you want to continue?', 'tokenico'),
            'invalidContractAddress' => esc_html__('Invalid contract address', 'tokenico'),
            'notAcceptedChains' => esc_html__('The current network is not added to the list of allowed networks. To be able to use the network, please add it to the allowed networks in the settings first.', 'tokenico'),
            'notAcceptedWallet' => esc_html__('The wallet you want to connect to is not accepted.', 'tokenico'),
            'walletNotDetected' => esc_html__('The wallet you want to connect to could not be detected!', 'tokenico'),
            'connectionRefused' => esc_html__('Connection refused', 'tokenico'),
            'bigStartDate' => esc_html__('The start date cannot be greater than the end date.', 'tokenico'),
            'bigMinContribution' => esc_html__('The minimum contribution cannot be greater than the maximum contribution.', 'tokenico'),
            'bigMinMaxContribution' => esc_html__('Minimum contribution and maximum contribution cannot exceed the total sales limit!', 'tokenico'),
            'deployContract' => esc_html__('Contract being deployed please wait...', 'tokenico'),
            'saleApprove' => esc_html__('To be able to sell tokens, the contract address needs confirmation of use. Please confirm!', 'tokenico'),
            'invalidTokenAddress' => esc_html__('I think you entered an invalid token address. Please enter a valid token address.', 'tokenico'),
            'approveProcess' => esc_html__('Please wait for the approval process.', 'tokenico'),
            'approveProcessSuccess' => esc_html__('The approval process has been successfully completed and the presale will be published!', 'tokenico'),
            'approveProcessFailed' => esc_html__('Approval failed, please try again.', 'tokenico'),
            'intrinsicGasTooLow' => esc_html__('Intrinsic gas too low', 'tokenico'),
            'requestRejected' => esc_html__('Request rejected.', 'tokenico'),
            'insufficientBalance' => esc_html__('Insufficient balance.', 'tokenico'),
            "unexpectedError" => esc_html__('An unexpected error has occurred', 'tokenico'),
            'presaleConfirm' => esc_html__('You will receive %s1 %s2 tokens for %s3 %s4, confirm?', 'tokenico'),
            'buyNow' => esc_html__('Buy now', 'tokenico'),
            'pleaseEnterAmount' => esc_html__('Please enter an amount!', 'tokenico'),
            'areYouSure' => esc_html__('Are you sure?', 'tokenico'),
            'purchaseAmount' => esc_html__('Purchase amount :', 'tokenico'),
            "purchaseFailed"  => esc_html__("An error occurred during the purchase!", 'tokenico'),
            "purchaseSuccess1"  => esc_html__("Purchase completed successfully! Tokens will be sent to your account shortly!", 'tokenico'),
            "purchaseSuccess2"  => esc_html__("Purchase completed successfully! After the presale is over, you can claim tokens with the claim button!", 'tokenico'),
            "claim"  => esc_html__("Claim", 'tokenico'),
            "requestRejected" => esc_html__("Request rejected", 'tokenico'),
            "claimSuccessful" => esc_html__("The operation completed successfully. The tokens you purchased will be reflected in your account shortly.", "tokenico"),
            "metaMaskNotDetected" => esc_html__("The MetaMask you want to connect to could not be detected!", "tokenico"),
            'successCopy' => esc_html__('Copying to clipboard was successful!', 'tokenico'),
            'errorCoppy' => esc_html__('Could not copy text: ', 'tokenico'),
            'saleBalanceError' => esc_html__('There is not enough balance in your wallet for the token you want to sell!', 'tokenico'),
            'insufficientLiquidity' => esc_html__('Insufficient liquidity by the seller.', 'tokenico'),
            'claimConfirm' => esc_html__('A total of %s1 %s2 tokens that you have purchased will be sent to your address.', 'tokenico'),
            'continue' => esc_html__('Continue', 'tokenico'),
            'getDatesError' => esc_html__('There was a problem setting the dates, please refresh the page and try again.', 'tokenico'),
            'alreadyProcessing' => esc_html__("A connection request is already pending, check the wallet plugin!", 'tokenico'),
            'transferAmount' => esc_html__('The transfer amount cannot be less than zero.', 'tokenico')
        ];
    }

}